### ISSUE TITLE
It doesn't work with 4D v17 and upper

### ISSUE THREAD

**Issue by NachoBracho** [miyako/4d-plugin-simple-postgres-client#1]
The latest version of 4D that can load the plugin es v16 R6, both Mac and Windows.

On v17 and upper it says "The executable could not be loaded", and it is marked as "Disabled".

**Comment by miyako** [comment]
needs update

* libpq.5.8.dylib
* libjson.7.6.1.dylib

**Comment by miyako** [comment]
could you please try v2?

the syntax is different (object and collection support)

https://github.com/miyako/4d-plugin-simple-postgres-client-v2/releases

**Comment by NachoBracho** [comment]
Hi:

At first glance it works flawlessly!, and the collection and object support is a great bonus!

Nevertheless, I want to test it again at home, with some old databases. I remember some problems with parameters when using UUID identifiers but I cannot remember what happened exactly. So I will test it to be sure for the release.


Thank you again!

Nacho Bracho

**Comment by NachoBracho** [comment]
Hi!

It seems that the plugin does not work with Macintosh (v17, v18). At least with High Sierra.

In the plugin tab in the Explorer, it says in red:
Disabled
The executable could not be loaded.

Even, with a Windows Server, the Windows client works, but the the Mac client doesn't.

Nacho Bracho

**Comment by miyako** [comment]
Hello, thank you for the feed back, very much appreciated!

Can you specify which build of the plugin you used?

I ask, because it could be a difference between dynamic or static linkage, and I need to know.

https://github.com/miyako/4d-plugin-simple-postgres-client/releases
https://github.com/miyako/4d-plugin-simple-postgres-client-v2/releases

**Comment by NachoBracho** [comment]
I tried V2, but I have just tried the new V1 and it shows the same problem.

**Comment by miyako** [comment]
Thank you, but could you please post the exact hyperlink

**Comment by miyako** [comment]
Also, could you please clarify whether you tested Catalina or if you tried High Sierra only.

Also I need to know the 4D version and build number.

I understand it is not fun, but such information are critical.

**Comment by NachoBracho** [comment]
Happy to help!

I am using the main links for the latest releases. Also I tried .zip and .dmg

For V1:
https://github.com/miyako/4d-plugin-simple-postgres-client/releases/download/1.0.v18/Simple.PostgreSQL.Client.zip
https://github.com/miyako/4d-plugin-simple-postgres-client/releases/download/1.0.v17/Simple.PostgreSQL.Client.zip

For V2:
https://github.com/miyako/4d-plugin-simple-postgres-client-v2/releases/download/2.0.v18/Simple.PostgreSQL.Client.zip
https://github.com/miyako/4d-plugin-simple-postgres-client-v2/releases/download/2.0.v17/Simple.PostgreSQL.Client.zip


4D v18 build 18.246707
4D v17 build 17.248004 64-bit

OSX 10.13.6. High Sierra.

I have not Catalina yet.

**Comment by miyako** [comment]
it might be an SDK compatibility issue.

/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)

I would need to use an older version of Xcode and an older SDK. 
(and then notarise it with the current version of Xcode tools)
it's a lot of work.

**Comment by miyako** [comment]
I think it is OpenSSL missing symbol on 10.13

```
MacOS: 10.13.6 Symbol not found: ____chkstk_darwin
```

**Comment by miyako** [comment]
please find the releases that have "mojave" in their names (not tested).

**Comment by NachoBracho** [comment]
Great! These releases work fine. They load, connect and retrieve in v17 and v18 with High Sierra.

Should I try something else for you to close it?

I'm going to test parameters binding, because I had some problems in the old version with UUID parameters. If something goes wrong I'll open a new issue.
