### ISSUE TITLE
parameter count is incorrect (n-1)

### ISSUE THREAD

**Issue by miyako** [miyako/4d-plugin-simple-postgres-client#1]
since switching to collection

**Comment by miyako** [comment]
fixed in 2.1

**Comment by NachoBracho** [comment]
It's strange, but it still doesn't work with just 1 parameter.

Fixed for 2 or more parameters.

**Comment by miyako** [comment]
should be fixed in 2.2

**Comment by NachoBracho** [comment]
Hello again!

Parameters count is fixed, but the values are wrong.

**Macintosh:** all parameters get the same value, corresponding to the value from the last parameter.
**Windows:** all parameters have empty values.

Here you have a method to test it:

[PG_test_2.txt](https://github.com/miyako/4d-plugin-simple-postgres-client-v2/files/4271606/PG_test_2.txt)

**Comment by miyako** [comment]
Hello, thanks for the sample DB and code,  I found the bug, a fix should be posted soon.

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-simple-postgres-client-v2/releases/tag/2.2.n

**Comment by NachoBracho** [comment]
It's ok. The parameter count issue is fixed. I'll test it a little more, but I think that the new version is working.
