### ISSUE TITLE
One parameter is skipped when sending the bound parameters

### ISSUE THREAD

**Issue by NachoBracho** [miyako/4d-plugin-simple-postgres-client#2]
A query with 1 parameter returns:
`ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1`

A query with 2 parameters returns:
`ERROR:  bind message supplies 1 parameters, but prepared statement "" requires 2`

Broken after the change from array to collection.

Please find attached a method with a test connection to a test server.

[PG_test.txt](https://github.com/miyako/4d-plugin-simple-postgres-client/files/4263440/PG_test.txt)

[PG_test.c4d.zip](https://github.com/miyako/4d-plugin-simple-postgres-client/files/4263436/PG_test.c4d.zip)

**Comment by miyako** [comment]
I think I found the mistake, but I don't have access to Mojave.
Let's see if using the older version of OpenSSL on Catalina Xcode works for you.

**Comment by miyako** [comment]
the issue should be reported for v2

https://github.com/miyako/4d-plugin-simple-postgres-client-v2/issues/1
